### ISSUE TITLE
1.8.9 Test Server

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemise/Simply-Magic-2#1]
I am opening up a test server for 1.8.9 mods in the port of Simply Magic. There will be no quests, rather this is a place for you all to gather information on how the mods work and provide feedback on what new parts of the mods will need quests or any mod additions. If you are interested, I will white list you and anybody you wish to bring along. Thanks!

**Comment by DrasticDemise** [comment]
@Fortanono @Zieg777 @TDarkShadow @Mechalith

You all down for some server play?

**Comment by Mechalith** [comment]
I'd be down, sure.

On Sat, Feb 6, 2016 at 9:26 AM, DrasticDemise notifications@github.com
wrote:

> @Fortanono https://github.com/Fortanono @Zieg777
> https://github.com/Zieg777 @TDarkShadow https://github.com/TDarkShadow
> @Mechalith https://github.com/Mechalith
> 
> You all down for some server play?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DrasticDemise/Simply-Magic-2/issues/1#issuecomment-180815348
> .

## 

Sisyphus had it easy...

**Comment by Fortanono** [comment]
IGN is AquaBuzzardHR (YT channel that I didn't want to associate with my main username for reasons), would love to play.

Might not be on that often though, have several other projects...

**Comment by DrasticDemise** [comment]
I will have the server up this week and add those that are interested.

**Comment by DrasticDemise** [comment]
Moved to Forum PM
