### ISSUE TITLE
Darklands blindness flickering on and off

### ISSUE THREAD

**Issue by extinak** [DrasticDemise/Simply-Magic-2#12]
I have several Abyssalcraft biomes near my spawn. I'm getting a blindness status effect every couple seconds that lasts for only a few seconds, so it flips on and off. I am not familiar with Abyssalcraft and do not know if this is intended behavior or not.

**Comment by Zieg777** [comment]
I think it is. It's "darklands" for a reason. I haven't progressed much to know if there is a way to counter this further in the mod.

**Comment by DrasticDemise** [comment]
Yes, this is intended behavior of the mod, it is inflicted by being in that biome.
