### ISSUE TITLE
FPS Issues with Grave's mod "spirits"

### ISSUE THREAD

**Issue by extinak** [DrasticDemise/Simply-Magic-2#15]
After I die and go back to open the grave, and the "spirit" comes out and attacks me, my fps drops to around ~5. This lasts until I leave the area that the grave is in. Since I'm testing around my spawn, the slowdown lasts until I walk away from my house. I tested this case around ~20ish times. Each time the slowdown started after I popped open the grave with a spirit in it. It does not happen if the grave is empty (minus items of course). These cases were tested with mostly an empty inventory.

**Comment by DrasticDemise** [comment]
This zombie will be disabled next patch. Thanks for the report.
