### ISSUE TITLE
Graves mod "spirits" are too overpowered

### ISSUE THREAD

**Issue by Zieg777** [DrasticDemise/Simply-Magic-2#16]
It is supposed to be a rare occurance that "the spirits" come and attack you.

I get it almost every time, and they single shot me. Two shots maybe if I'm in armor. There needs to be a way to tone down or disable entirely these spawns. If I have even half a second of lag while breaking open my grave, I'll die before I even know one spawned. This isn't weak armor I'm wearing either.

**Comment by DrasticDemise** [comment]
These should be disabled on the latest version?
