### ISSUE TITLE
Chisel blocks break instantly with fist and disappear

### ISSUE THREAD

**Issue by ArbitraryHubris** [DrasticDemise/Simply-Magic-2#22]
Something is amiss with this version of chisel.  If you break chisel blocks with a pick, the break almost instantly but they do appear as item entities.  If you, however, break them with your fist, they break almost instantly and then do not drop as entities.

**Comment by ArbitraryHubris** [comment]
I haven't tried this with every type of block that has been chiseled - this is what I'm seeing with chiseled cobble.

**Comment by DrasticDemise** [comment]
Chisel is unfinished, will be fixed with the mod.
